export const MOCK_PLAYERS = [
  { address: "0xabc123...def", name: "CryptoGamer99" },
  { address: "0x789ghi...jkl", name: "Web3Warrior" },
  { address: "0x456mno...pqr", name: "PixelKnight" },
];

export const MOCK_PUBLISHERS = [
  {
    id: "pub-001",
    suiPublisherId: "0xpub001",
    name: "IndieQuest Studios",
    logoUrl: null,
    isVerified: true,
    createdAt: "2026-06-10T00:00:00Z",
    gameCount: 2,
  },
  {
    id: "pub-002",
    suiPublisherId: "0xpub002",
    name: "Elden Realms Inc.",
    logoUrl: null,
    isVerified: false,
    createdAt: "2026-06-15T00:00:00Z",
    gameCount: 1,
  },
  {
    id: "pub-003",
    suiPublisherId: "0xpub003",
    name: "Pixelverse Games",
    logoUrl: null,
    isVerified: true,
    createdAt: "2026-06-12T00:00:00Z",
    gameCount: 1,
  },
];

export const MOCK_GAMES = [
  {
    id: 1,
    suiGameId: "0xgame001",
    publisherId: "pub-001",
    publisherName: "IndieQuest Studios",
    name: "Astral Quest RPG",
    description: "An epic fantasy RPG where every dungeon drop is truly yours.",
    genre: "RPG",
    websiteUrl: "https://astralquest.game",
    status: "published" as const,
    gameCapabilityId: "0xcap001",
    itemCount: 15,
    draftItemCount: 3,
    publishedItemCount: 12,
    createdAt: "2026-06-10T00:00:00Z",
  },
  {
    id: 2,
    suiGameId: null,
    publisherId: "pub-001",
    publisherName: "IndieQuest Studios",
    name: "CyberForge Online",
    description: "Cyberpunk MMO with true asset ownership.",
    genre: "MMO",
    websiteUrl: null,
    status: "draft" as const,
    gameCapabilityId: null,
    itemCount: 5,
    draftItemCount: 5,
    publishedItemCount: 0,
    createdAt: "2026-06-18T00:00:00Z",
  },
  {
    id: 3,
    suiGameId: "0xgame003",
    publisherId: "pub-002",
    publisherName: "Elden Realms Inc.",
    name: "Elden Realms",
    description: "Dark fantasy universe with legendary loot.",
    genre: "Action RPG",
    websiteUrl: "https://eldenrealms.game",
    status: "published" as const,
    gameCapabilityId: "0xcap003",
    itemCount: 8,
    draftItemCount: 0,
    publishedItemCount: 8,
    createdAt: "2026-06-15T00:00:00Z",
  },
  {
    id: 4,
    suiGameId: "0xgame004",
    publisherId: "pub-003",
    publisherName: "Pixelverse Games",
    name: "PixelCraft Arena",
    description: "Retro-style arena battler with tradable pixel cosmetics.",
    genre: "Battle Arena",
    websiteUrl: null,
    status: "published" as const,
    gameCapabilityId: "0xcap004",
    itemCount: 6,
    draftItemCount: 0,
    publishedItemCount: 6,
    createdAt: "2026-06-12T00:00:00Z",
  },
];

export const MOCK_ITEMS = [
  {
    id: "item-001",
    suiItemId: "0xitem001",
    gameId: 1,
    gameName: "Astral Quest RPG",
    name: "Legendary Void Sword",
    itemType: "Weapon",
    rarity: "Legendary",
    description: "Forged in the void between stars. Cuts through any armor.",
    imageUrl: "/api/placeholder/400/400",
    blobId: "item_void_sword",
    supply: null as null | number,
    isNft: true,
    attributes: { strength: "18", element: "void", durability: "95" },
    status: "published" as const,
    owner: "0xabc123...def",
    createdAt: "2026-06-11T00:00:00Z",
  },
  {
    id: "item-002",
    suiItemId: "0xitem002",
    gameId: 1,
    gameName: "Astral Quest RPG",
    name: "Aetherial Staff of Wisdom",
    itemType: "Staff",
    rarity: "Epic",
    description: "Channeled with ancient aether energy. Boosts magic by 40%.",
    imageUrl: "/api/placeholder/400/400",
    blobId: "item_aether_staff",
    supply: null as null | number,
    isNft: true,
    attributes: { magic: "40", element: "aether", wisdom: "12" },
    status: "published" as const,
    owner: "0xabc123...def",
    createdAt: "2026-06-11T00:00:00Z",
  },
  {
    id: "item-003",
    suiItemId: "0xitem003",
    gameId: 1,
    gameName: "Astral Quest RPG",
    name: "Health Potion",
    itemType: "Consumable",
    rarity: "Common",
    description: "Restores 100 HP. Essential for any adventurer.",
    imageUrl: "/api/placeholder/400/400",
    blobId: "item_dragon_scale",
    supply: 1000,
    isNft: false,
    attributes: { heal: "100", weight: "0.5" },
    status: "published" as const,
    owner: "0xabc123...def",
    createdAt: "2026-06-11T00:00:00Z",
  },
  {
    id: "item-004",
    suiItemId: "0xitem004",
    gameId: 3,
    gameName: "Elden Realms",
    name: "Divine Bow of Light",
    itemType: "Bow",
    rarity: "Legendary",
    description: "Blessed by the ancients. Arrows pierce darkness.",
    imageUrl: "/api/placeholder/400/400",
    blobId: "item_ghost_cloak",
    supply: null as null | number,
    isNft: true,
    attributes: { attack: "25", element: "light", range: "300" },
    status: "published" as const,
    owner: "0x789ghi...jkl",
    createdAt: "2026-06-16T00:00:00Z",
  },
  {
    id: "item-005",
    suiItemId: "0xitem005",
    gameId: 3,
    gameName: "Elden Realms",
    name: "Iron Shield of Grom",
    itemType: "Shield",
    rarity: "Rare",
    description: "Standard-issue dwarven shield. Reliable and sturdy.",
    imageUrl: "/api/placeholder/400/400",
    blobId: "item_pixel_blade",
    supply: null as null | number,
    isNft: true,
    attributes: { defense: "60", weight: "15", durability: "200" },
    status: "published" as const,
    owner: "0x789ghi...jkl",
    createdAt: "2026-06-16T00:00:00Z",
  },
  {
    id: "item-006",
    suiItemId: "0xitem006",
    gameId: 4,
    gameName: "PixelCraft Arena",
    name: "Chronos Pixel Mirror",
    itemType: "Cosmetic",
    rarity: "Epic",
    description: "Reflects your past victories. Purely cosmetic flex.",
    imageUrl: "/api/placeholder/400/400",
    blobId: "item_necro_tome",
    supply: null as null | number,
    isNft: true,
    attributes: { effect: "time_warp", tier: "3" },
    status: "published" as const,
    owner: "0x456mno...pqr",
    createdAt: "2026-06-13T00:00:00Z",
  },
];

export const MOCK_DRAFT_ITEMS = [
  {
    id: "draft-001",
    suiItemId: null,
    gameId: 1,
    gameName: "Astral Quest RPG",
    name: "Thunder Gauntlets",
    itemType: "Gauntlets",
    rarity: "Epic",
    description: "Shock your enemies with electrifying punches.",
    imageUrl: "/api/placeholder/400/400",
    blobId: null,
    supply: null as null | number,
    isNft: true,
    attributes: { element: "thunder", attack: "15", speed: "8" },
    status: "draft" as const,
    owner: null,
    createdAt: "2026-06-18T00:00:00Z",
  },
  {
    id: "draft-002",
    suiItemId: null,
    gameId: 1,
    gameName: "Astral Quest RPG",
    name: "Shadow Cloak",
    itemType: "Armor",
    rarity: "Rare",
    description: "Become one with the shadows.",
    imageUrl: "/api/placeholder/400/400",
    blobId: null,
    supply: null as null | number,
    isNft: true,
    attributes: { defense: "10", effect: "stealth" },
    status: "draft" as const,
    owner: null,
    createdAt: "2026-06-18T00:00:00Z",
  },
  {
    id: "draft-003",
    suiItemId: null,
    gameId: 2,
    gameName: "CyberForge Online",
    name: "Neon Katana",
    itemType: "Weapon",
    rarity: "Legendary",
    description: "A blade forged from pure neon light.",
    imageUrl: "/api/placeholder/400/400",
    blobId: null,
    supply: null as null | number,
    isNft: true,
    attributes: { element: "neon", attack: "30", speed: "20" },
    status: "draft" as const,
    owner: null,
    createdAt: "2026-06-19T00:00:00Z",
  },
];

export const MOCK_LISTINGS = [
  {
    id: "listing-001",
    item: MOCK_ITEMS[1],
    price: 12.5,
    seller: "0xabc123...def",
    sellerName: "CryptoGamer99",
    listingType: "sale" as const,
    royaltyBps: 300,
    createdAt: "2026-06-17T00:00:00Z",
  },
  {
    id: "listing-002",
    item: MOCK_ITEMS[3],
    price: 28.0,
    seller: "0x789ghi...jkl",
    sellerName: "Web3Warrior",
    listingType: "sale" as const,
    royaltyBps: null,
    createdAt: "2026-06-18T00:00:00Z",
  },
];

export const MOCK_ESCROWS = [
  {
    id: "escrow-001",
    offeredItem: MOCK_ITEMS[0],
    initiator: "0xabc123...def",
    initiatorName: "CryptoGamer99",
    conditions: {
      itemTypeAccept: "Weapon",
      rarityAccept: "Legendary",
      gameIdAccept: null as null | number,
      itemIdTarget: null as null | string,
    },
    counterparty: null,
    isActive: true,
    createdAt: "2026-06-18T00:00:00Z",
  },
  {
    id: "escrow-002",
    offeredItem: MOCK_ITEMS[4],
    initiator: "0x789ghi...jkl",
    initiatorName: "Web3Warrior",
    conditions: {
      itemTypeAccept: "Cosmetic",
      rarityAccept: "Epic",
      gameIdAccept: null as null | number,
      itemIdTarget: null as null | string,
    },
    counterparty: null,
    isActive: true,
    createdAt: "2026-06-19T00:00:00Z",
  },
];

export const MOCK_CLAIM_CODES = [
  {
    code: "XK92-BH4M",
    gameId: 1,
    gameName: "Astral Quest RPG",
    itemTemplate: MOCK_ITEMS[0],
    expiresAt: "2026-06-21T00:00:00Z",
    claimedAt: null,
    claimedBy: null,
  },
  {
    code: "ZZ00-XXXX",
    gameId: 3,
    gameName: "Elden Realms",
    itemTemplate: MOCK_ITEMS[3],
    expiresAt: "2026-06-10T00:00:00Z",
    claimedAt: "2026-06-09T00:00:00Z",
    claimedBy: "0xabc123...def",
  },
];

export const MOCK_API_KEYS = [
  {
    id: 1,
    prefix: "morita_sk_****abcd",
    isActive: true,
    lastUsedAt: "2026-06-18T00:00:00Z",
    createdAt: "2026-06-10T00:00:00Z",
  },
  {
    id: 2,
    prefix: "morita_sk_****efgh",
    isActive: false,
    lastUsedAt: null,
    createdAt: "2026-06-12T00:00:00Z",
  },
];

export const MOCK_TX_EVENTS = [
  { id: 1, txHash: "0xeea01a...", eventType: "ItemMinted", description: "Minted Legendary Void Sword to 0xabc1...def", timestamp: "2026-06-17T14:30:00Z" },
  { id: 2, txHash: "0xbb02bb...", eventType: "ItemSold", description: "Sold Aetherial Staff for 12.5 SUI", timestamp: "2026-06-17T15:45:00Z" },
  { id: 3, txHash: "0xcc03cc...", eventType: "EscrowFulfilled", description: "Barter complete: Void Katana ↔ Divine Bow", timestamp: "2026-06-18T09:20:00Z" },
  { id: 4, txHash: "0xdd04dd...", eventType: "ItemMinted", description: "Minted Iron Shield to 0x789g...jkl", timestamp: "2026-06-18T11:00:00Z" },
  { id: 5, txHash: "0xee05ee...", eventType: "ItemListed", description: "Listed Chronos Mirror for 5 SUI", timestamp: "2026-06-18T16:30:00Z" },
  { id: 6, txHash: "0xff06ff...", eventType: "EscrowCreated", description: "Created barter: Legendary Void Sword ↔ any Legendary Weapon", timestamp: "2026-06-19T08:00:00Z" },
  { id: 7, txHash: "0xgg07gg...", eventType: "ItemClaimed", description: "Claimed Health Potion from Astral Quest RPG", timestamp: "2026-06-19T10:15:00Z" },
];

export const MOCK_PUBLISHER_ACTIVITIES = [
  ...MOCK_TX_EVENTS.filter((e) => ["ItemMinted", "ItemListed", "ItemClaimed"].includes(e.eventType)),
  { id: 8, txHash: "—", eventType: "GameCreated", description: "Published CyberForge Online (draft)", timestamp: "2026-06-18T10:00:00Z" },
  { id: 9, txHash: "—", eventType: "GamePublished", description: "Astral Quest RPG deployed to Sui Testnet", timestamp: "2026-06-10T00:00:00Z" },
];

export const MOCK_ANALYTICS = {
  totalMinted: 42,
  totalClaimed: 38,
  activePlayers: 156,
  txVolume: 1280,
  claimConversionRate: 90.5,
};
